### ISSUE TITLE
update Code of Conduct contact information

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/.github#16]
In the current Code of Conduct, 

My personal email should be removed from section 6.

In section 8 (Addressing Grivances) and in 10 (Contact Info) you are told to message leadership@blackpythondevs.com

This should be changed to coc@blackpythondevs.com

**Comment by mbuguadouglas** [comment]
I'd like to handle this issue 😄

**Comment by mbvgua** [comment]
I think this issue needs to be closed.
