### ISSUE TITLE
Add Code of Conduct

### ISSUE THREAD

**Issue by kjaymiller** [BlackPythonDevs/.github#3]
We need to add the code of conduct that our community follows to this repo.

That can be found - https://gist.github.com/kjaymiller/7c03e2ab9c76daa330cb76d383c3c67a

**Comment by oleksis** [comment]
Add the raw file or as submodule: https://github.com/oleksis/BlackPythonDevs.github/commit/7e1faed51dfa403ab4064d8e52303e2cd79bdbd5

**Comment by kjaymiller** [comment]
also fixes #5

**Comment by kjaymiller** [comment]
> Add the raw file or as submodule: [oleksis@7e1faed](https://github.com/oleksis/BlackPythonDevs.github/commit/7e1faed51dfa403ab4064d8e52303e2cd79bdbd5) ?

I misread. Add the raw file
